# Generated by Django 3.0.2 on 2020-01-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API', '0002_delete_brandmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('BrandID', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'BrandMaster',
            },
        ),
    ]
