# Generated by Django 2.0.6 on 2020-02-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200219_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedtl',
            name='InterActionDateTime',
            field=models.DateTimeField(default='2020-02-23 23:48:13'),
        ),
        migrations.AlterField(
            model_name='devicedtl',
            name='CameraClick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedtl',
            name='OtherClick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedtl',
            name='RAMClick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedtl',
            name='StorageClick',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
