# Generated by Django 3.0.2 on 2020-01-30 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_brandmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMaster',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('ModelName', models.CharField(max_length=20)),
                ('isactive', models.BooleanField(default=True)),
                ('BrandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.BrandMaster')),
            ],
            options={
                'db_table': 'ModelMaster',
            },
        ),
    ]
