# Generated by Django 2.0.6 on 2020-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200223_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedtl',
            old_name='CameraClick',
            new_name='Back_CameraClick',
        ),
        migrations.AddField(
            model_name='devicedtl',
            name='ColorClick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedtl',
            name='Front_CameraClick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedtl',
            name='ScreenSizeClick',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicedtl',
            name='InterActionDateTime',
            field=models.DateTimeField(default='2020-02-24 17:01:00'),
        ),
    ]
